### PR TITLE
Feat/haystack import

### PR DESCRIPTION
**Pull request by TShapinsky**
Fix haystack export when haystack model is imported.

### CODE REVIEW

**Comment by MatthewSteen** [comment]
I was able to import, add an AHU, then export the MedOfc hayson file, but when I re-imported it I got an error. Looks like it's related to the site.

```
Traceback (most recent call last):
  File "/hasty/hasty/lib/deserialization.py", line 87, in save_site
    models.Site.objects.get(id=site_id)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 415, in get
    raise self.model.DoesNotExist(

During handling of the above exception (Site matching query does not exist.), another exception occurred:
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)

The above exception (value too long for type character varying(2)

**Comment by TShapinsky** [comment]
> I was able to import, add an AHU, then export the MedOfc hayson file, but when I re-imported it I got an error. Looks like it's related to the site.
> 
> ```
> Traceback (most recent call last):
>   File "/hasty/hasty/lib/deserialization.py", line 87, in save_site
>     models.Site.objects.get(id=site_id)
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 415, in get
>     raise self.model.DoesNotExist(
> 
> During handling of the above exception (Site matching query does not exist.), another exception occurred:
>   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
>     return self.cursor.execute(sql, params)
> 
> The above exception (value too long for type character varying(2)

Looks like this is because Hasty adds a `state: "s:None"` to the export. It then freaks out when trying to parse that string into a two character State abbreviation.

**Comment by MatthewSteen** [comment]
I removed the state choice and it looks like there might be something else going on with the ID. 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/hasty/hasty/generate/views.py", line 32, in post
    file_processing(file)
  File "/hasty/hasty/lib/deserialization.py", line 207, in file_processing
    handle_haystack(data)
  File "/hasty/hasty/lib/deserialization.py", line 22, in handle_haystack
    save_ahus(ahus, site_id, terminal_units,
  File "/hasty/hasty/lib/deserialization.py", line 99, in save_ahus
    site = models.Site.objects.get(id=site_id)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 415, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /
Exception Value: Site matching query does not exist.
```

**Comment by TShapinsky** [comment]
> I removed the state choice and it looks like there might be something else going on with the ID.
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/hasty/hasty/generate/views.py", line 32, in post
>     file_processing(file)
>   File "/hasty/hasty/lib/deserialization.py", line 207, in file_processing
>     handle_haystack(data)
>   File "/hasty/hasty/lib/deserialization.py", line 22, in handle_haystack
>     save_ahus(ahus, site_id, terminal_units,
>   File "/hasty/hasty/lib/deserialization.py", line 99, in save_ahus
>     site = models.Site.objects.get(id=site_id)
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 415, in get
>     raise self.model.DoesNotExist(
> 
> Exception Type: DoesNotExist at /
> Exception Value: Site matching query does not exist.
> ```

This is happening because the model being imported has the same ID as a model which is already in the database. I think at this point this should probably be a separate issue. We'd want to think about the use case where an exported model is being imported.

**Review by MatthewSteen — APPROVED** [review]

**Pull request merged**
